language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - pylint cryptofield
  - python -m unittest tests
  - set PYTHONPATH=.
  - for f in examples/*.py; do python "$f"; done