language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pylint cryptofield
  - pytype cryptofield
  - python -m unittest discover -s tests
  - for f in examples/*.py; do python "$f"; done